# Data Understanding

In [2]:
import pandas as pd

df_k1 = pd.read_csv('../data/raw/mamikos-2026-09-07-ukrida-kampus-1.csv')
df_k2 = pd.read_csv('../data/raw/mamikos-2026-09-09-ukrida-kampus-2.csv')

print(f"Ukuran Raw Kampus 1: {df_k1.shape}")
print(f"Ukuran Raw Kampus 2: {df_k2.shape}")

Ukuran Raw Kampus 1: (2231, 29)
Ukuran Raw Kampus 2: (2340, 28)

In [3]:
display(df_k1.head(5))

,bg-c-picture__img src,bg-c-image__img src,bg-c-image__img src (2),bg-c-text,tipe,bg-u-ml-xs,nama_kost,lokasi,track-list-booking-kost,rc-facilities_divider,...,rc-facilities_divider (5),track-list-booking-kost (6),rc-facilities__rating-text,bg-u-ml-xxxs,rc-price__additional-discount,rc-price__additional-discount-price,bg-c-picture__img src (2),rc-price__other-promo-label,rc-price__long-term-rate,bg-c-text (2)
0,https://static.mamikos.com/uploads/cache/data/...,https://static.mamikos.com/uploads/cache/data/...,https://mamikos.com/general/img/icons/ic_kos_a...,Dilihat 500+ kali,Putri,Sisa 1 kamar,Kost Kangaroom Premium,Kecamatan Grogol petamburan,K. Mandi Dalam,·,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://static.mamikos.com/uploads/cache/data/...,https://static.mamikos.com/uploads/cache/data/...,https://mamikos.com/general/img/icons/ic_kos_a...,Dilihat 500+ kali,Putri,Sisa 1 kamar,Kost Co Living Rustanto Residence Susilo Tipe A,Grogol Petamburan,K. Mandi Dalam,·,...,·,Akses 24 Jam,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://static.mamikos.com/uploads/cache/data/...,https://static.mamikos.com/uploads/cache/data/...,https://mamikos.com/general/img/icons/ic_kos_a...,Dilihat 500+ kali,Campur,Sisa 1 kamar,Kost Tomang Amber Residence Royal,Kecamatan Grogol petamburan,K. Mandi Dalam,·,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://static.mamikos.com/uploads/cache/data/...,https://static.mamikos.com/uploads/cache/data/...,https://mamikos.com/general/img/icons/ic_kos_a...,Dilihat 500+ kali,Campur,NaN,Kost Cozy Coliving Wijaya Kusuma Jelambar Deluxe,Kecamatan Grogol petamburan,K. Mandi Dalam,·,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://static.mamikos.com/uploads/cache/data/...,https://static.mamikos.com/uploads/cache/data/...,https://mamikos.com/general/img/icons/ic_kos_a...,Dilihat 500+ kali,Campur,Sisa 3 kamar,Kost Sukha Residence Tanjung Duren Tipe Deluxe...,Grogol Petamburan,K. Mandi Dalam,·,...,·,Akses 24 Jam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df_k1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2231 entries, 0 to 2230
Data columns (total 29 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   bg-c-picture__img src                2231 non-null   object
 1   bg-c-image__img src                  2231 non-null   object
 2   bg-c-image__img src (2)              1731 non-null   object
 3   bg-c-text                            1980 non-null   object
 4   tipe                                 2231 non-null   object
 5   bg-u-ml-xs                           1083 non-null   object
 6   nama_kost                            2231 non-null   object
 7   lokasi                               2231 non-null   object
 8   track-list-booking-kost              2231 non-null   object
 9   rc-facilities_divider                2230 non-null   object
 10  track-list-booking-kost (2)          2230 non-null   object
 11  rc-facilities_divider (2)            2207 non-null   object
 12  track-list-booking-kost (3)          2207 non-null   object
 13  rc-facilities_divider (3)            2109 non-null   object
 14  track-list-booking-kost (4)          2109 non-null   object
 15  rc-facilities_divider (4)            1992 non-null   object
 16  track-list-booking-kost (5)          1992 non-null   object
 17  harga                                2231 non-null   object
 18  tipe_                                2231 non-null   object
 19  rc-facilities_divider (5)            1390 non-null   object
 20  track-list-booking-kost (6)          1390 non-null   object
 21  rc-facilities__rating-text           1192 non-null   float64
 22  bg-u-ml-xxxs                         752 non-null    object
 23  rc-price__additional-discount        542 non-null    object
 24  rc-price__additional-discount-price  542 non-null    object
 25  bg-c-picture__img src (2)            649 non-null    object
 26  rc-price__other-promo-label          344 non-null    object
 27  rc-price__long-term-rate             119 non-null    object
 28  bg-c-text (2)                        12 non-null     object
dtypes: float64(1), object(28)
memory usage: 505.6+ KB

In [5]:
print(df_k1.isnull().sum())

bg-c-picture__img src                     0
bg-c-image__img src                       0
bg-c-image__img src (2)                 500
bg-c-text                               251
tipe                                      0
bg-u-ml-xs                             1148
nama_kost                                 0
lokasi                                    0
track-list-booking-kost                   0
rc-facilities_divider                     1
track-list-booking-kost (2)               1
rc-facilities_divider (2)                24
track-list-booking-kost (3)              24
rc-facilities_divider (3)               122
track-list-booking-kost (4)             122
rc-facilities_divider (4)               239
track-list-booking-kost (5)             239
harga                                     0
tipe_                                     0
rc-facilities_divider (5)               841
track-list-booking-kost (6)             841
rc-facilities__rating-text             1039
bg-u-ml-xxxs                           1479
rc-price__additional-discount          1689
rc-price__additional-discount-price    1689
bg-c-picture__img src (2)              1582
rc-price__other-promo-label            1887
rc-price__long-term-rate               2112
bg-c-text (2)                          2219
dtype: int64

In [6]:
df_merged_temp = pd.concat([df_k1, df_k2], ignore_index=True)

total_raw = len(df_merged_temp)
duplikat_count = df_merged_temp.duplicated(subset=['nama_kost', 'harga']).sum()

print(f"Total Baris Gabungan Raw : {total_raw}")
print(f"Total Baris Duplikat     : {duplikat_count} ({round(duplikat_count/total_raw*100, 2)}%)")
print(f"Estimasi Data Unik       : {total_raw - duplikat_count}")

Total Baris Gabungan Raw : 4571
Total Baris Duplikat     : 4215 (92.21%)
Estimasi Data Unik       : 356

In [7]:
# SEL 5: Inspeksi Sample Data Duplikat
df_merged_temp[df_merged_temp.duplicated(subset=['nama_kost', 'harga'], keep=False)].sort_values('nama_kost').head(10)

,bg-c-picture__img src,bg-c-image__img src,bg-c-image__img src (2),bg-c-text,tipe,bg-u-ml-xs,nama_kost,lokasi,track-list-booking-kost,rc-facilities_divider,...,rc-facilities_divider (5),track-list-booking-kost (6),rc-facilities__rating-text,bg-u-ml-xxxs,rc-price__additional-discount,rc-price__additional-discount-price,bg-c-picture__img src (2),rc-price__other-promo-label,rc-price__long-term-rate,bg-c-text (2)
4362,https://static.mamikos.com/uploads/cache/data/...,https://static.mamikos.com/uploads/cache/data/...,https://mamikos.com/general/img/icons/ic_kos_a...,Dilihat 500+ kali,Campur,Sisa 1 kamar,Kost 32 Residence Tipe A,Kebon Jeruk,K. Mandi Dalam,NaN,...,·,Akses 24 Jam,4.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2384,https://static.mamikos.com/uploads/cache/data/...,https://static.mamikos.com/uploads/cache/data/...,https://mamikos.com/general/img/icons/ic_kos_a...,Dilihat 500+ kali,Campur,Sisa 1 kamar,Kost 32 Residence Tipe A,Kebon Jeruk,K. Mandi Dalam,NaN,...,·,Akses 24 Jam,4.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2657,https://static.mamikos.com/uploads/cache/data/...,https://static.mamikos.com/uploads/cache/data/...,https://mamikos.com/general/img/icons/ic_kos_a...,Dilihat 500+ kali,Campur,Sisa 1 kamar,Kost 32 Residence Tipe A,Kebon Jeruk,K. Mandi Dalam,NaN,...,·,Akses 24 Jam,4.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2985,https://static.mamikos.com/uploads/cache/data/...,https://static.mamikos.com/uploads/cache/data/...,https://mamikos.com/general/img/icons/ic_kos_a...,Dilihat 500+ kali,Campur,Sisa 1 kamar,Kost 32 Residence Tipe A,Kebon Jeruk,K. Mandi Dalam,NaN,...,·,Akses 24 Jam,4.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3330,https://static.mamikos.com/uploads/cache/data/...,https://static.mamikos.com/uploads/cache/data/...,https://mamikos.com/general/img/icons/ic_kos_a...,Dilihat 500+ kali,Campur,Sisa 1 kamar,Kost 32 Residence Tipe A,Kebon Jeruk,K. Mandi Dalam,NaN,...,·,Akses 24 Jam,4.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4449,https://static.mamikos.com/uploads/cache/data/...,https://static.mamikos.com/uploads/cache/data/...,https://mamikos.com/general/img/icons/ic_kos_a...,Dilihat 500+ kali,Campur,Sisa 1 kamar,Kost 32 Residence Tipe A,Kebon Jeruk,K. Mandi Dalam,NaN,...,·,Akses 24 Jam,4.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3867,https://static.mamikos.com/uploads/cache/data/...,https://static.mamikos.com/uploads/cache/data/...,https://mamikos.com/general/img/icons/ic_kos_a...,Dilihat 500+ kali,Campur,Sisa 1 kamar,Kost 32 Residence Tipe A,Kebon Jeruk,K. Mandi Dalam,NaN,...,·,Akses 24 Jam,4.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3420,https://static.mamikos.com/uploads/cache/data/...,https://static.mamikos.com/uploads/cache/data/...,https://mamikos.com/general/img/icons/ic_kos_a...,Dilihat 500+ kali,Campur,Sisa 1 kamar,Kost 32 Residence Tipe A,Kebon Jeruk,K. Mandi Dalam,NaN,...,·,Akses 24 Jam,4.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4243,https://static.mamikos.com/uploads/cache/data/...,https://static.mamikos.com/uploads/cache/data/...,https://mamikos.com/general/img/icons/ic_kos_a...,Dilihat 500+ kali,Campur,Sisa 1 kamar,Kost 32 Residence Tipe A,Kebon Jeruk,K. Mandi Dalam,NaN,...,·,Akses 24 Jam,4.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4138,https://static.mamikos.com/uploads/cache/data/...,https://static.mamikos.com/uploads/cache/data/...,https://mamikos.com/general/img/icons/ic_room_...,Dilihat 500+ kali,Campur,Sisa 3 kamar,Kost 84 AL Tipe A,Palmerah,K. Mandi Dalam,NaN,...,·,Akses 24 Jam,5.0,NaN,Diskon 120rb,Rp1.525.000,https://static.mamikos.com/uploads/cache/data/...,NaN,NaN,NaN

In [10]:
df_tipe = df_merged_temp[df_merged_temp['nama_kost'].str.contains(r'(?i)\btipe\b', na=False)].copy()

df_tipe['suffix_tipe'] = df_tipe['nama_kost'].str.extract(r'(?i)\b(tipe\s+[a-z0-9\-_]+)', expand=False)

df_tipe['suffix_tipe'] = df_tipe['suffix_tipe'].str.title()

print(f"Total gabungan kost yang memiliki suffix tipe: {len(df_tipe)} baris\n")

print(df_tipe[['nama_kost', 'suffix_tipe', 'lokasi', 'harga']].head(15).to_string(index=False))

# Tampilkan sebaran tipe terbanyak
print("\nSebaran Suffix Tipe Terbanyak:")
print(df_tipe['suffix_tipe'].value_counts().head(10))

Total gabungan kost yang memiliki suffix tipe: 3883 baris

                                           nama_kost suffix_tipe            lokasi       harga
     Kost Co Living Rustanto Residence Susilo Tipe A      Tipe A Grogol Petamburan Rp2.750.000
Kost Sukha Residence Tanjung Duren Tipe Deluxe Barat Tipe Deluxe Grogol Petamburan Rp2.250.000
Kost Los Angeles Beverly Hills Labh Tipe Basic Barat  Tipe Basic Grogol Petamburan Rp2.500.000
               Kost Gelong Residence 27 Tipe B Barat      Tipe B Grogol Petamburan Rp2.870.000
               Kost Gelong Residence 27 Tipe A Barat      Tipe A Grogol Petamburan Rp2.770.000
                Kost Gichelle Residence Tipe B Barat      Tipe B Grogol Petamburan Rp2.141.000
                       Kost Shaka Plaza Slipi Tipe C      Tipe C          Palmerah Rp1.400.000
                       Kost Shaka Plaza Slipi Tipe B      Tipe B          Palmerah Rp2.035.000
      Kost Trinity Living Tipe B Tanjung Duren Barat      Tipe B Grogol Petamburan Rp2.482.000
                       Kost Shaka Plaza Slipi Tipe A      Tipe A          Palmerah Rp1.942.000
                Kost Gichelle Residence Tipe A Barat      Tipe A Grogol Petamburan Rp2.325.000
      Kost Trinity Living Tipe C Tanjung Duren Barat      Tipe C Grogol Petamburan Rp2.709.500
      Kost Trinity Living Tipe A Tanjung Duren Barat      Tipe A Grogol Petamburan Rp2.300.000
      Kost Trinity Living Tipe D Tanjung Duren Barat      Tipe D Grogol Petamburan Rp3.164.500
                     Kost Rss Residence Tipe C Barat      Tipe C Grogol Petamburan Rp2.175.000

Sebaran Suffix Tipe Terbanyak:
suffix_tipe
Tipe A           1286
Tipe B           1035
Tipe C            778
Tipe D            278
Tipe E             76
Tipe Deluxe        56
Tipe F             48
Tipe Standard      35
Tipe G             29
Tipe Royal         26
Name: count, dtype: int64